---
title: "Capstone Project"
author: "Alex V"
date: "May 13, 2015"
output: 
  html_document: 
    keep_md: yes
---

##Import 
```{r}
library(readr)
raw <- read_csv("C:/Users/Alex/1371_traffic_volumes.csv")
raw2 <- raw[-1:-2,] #remove extraneous rows (French and blank row) to allow "readr" to reparse variables types correctly
raw3 <- type_convert(raw2)
str(raw3) #check datatypes
```

##1: Initial Cleaning
```{r}
library(magrittr)
library(dplyr)

#rename columns
library(dplyr)
renamed.raw <- rename(raw3, "lhrs" = LHRS,"OS" =`O/S`, "year" = Year, "hwy.num" = `Hwy #`, "hwy.let" = `Hwy Let`, "hwy.type" = `Hwy Type (Text)`, "location" = `Location Description`, "reg" = Reg, "section.len" = `Section Length`, "conn.link.len" = `Connecting Link Length`, "sec.description" = `Secondary Description (for Connecting Links, Regional Boundarys,etc)`, "travel.pattern" = `Travel Pattern`, "dhv.percent" = `DHV %`, "directional.split" = `Directional Split`, "aadt" = AADT, "annual.aadt.change" = `Yearly % Change in AADT`, "decade.change" = `10 Year % Change in AADT`, "sadt" = SADT, "sawdt" = SAWDT, "wadt" = WADT)
```

```{r}
#checking for NAs
length(renamed.raw$lhrs)
length(renamed.raw$year)
length(renamed.raw$aadt)
sum(is.na(renamed.raw$aadt))
sum(is.na(renamed.raw$sadt))
sum(is.na(renamed.raw$sawdt))
sum(is.na(renamed.raw$wadt))
sum(renamed.raw$year=="9999")
#there are 553 NA entries for aadt. year is also set to 9999 for these entries
```
There are 553 incomplete entries. These entries are set to Year "9999" and have no values for AADT and the related variables.

```{r}
#removing NAs and duplicate entries
library(dplyr)
library(magrittr)
fil.data <- renamed.raw %>%
  distinct() %>%
  filter(year!="9999")

length(fil.data$year)
length(fil.data$aadt)

glimpse(renamed.raw)
```

There are `r length(fil.data$aadt)` remaining observations

##
``` {r}
library(dplyr)
library(ggvis)

filter1 <- select(fil.data, lhrs, year, aadt)

#sort lhrs by geographic proximity to city?

```

##2: Exploratory
```{r}
fil.data %>%
  group_by(lhrs) %>%
  summarise(avg=mean(aadt)) %>%
  ggvis(~lhrs, ~avg) %>%
  layer_points()
```

```{r}
library(pastecs)
library(dplyr)
explor.stat <- select (fil.data, aadt:wadt)
stat.desc(explor.stat)
```

```{r}
library(psych)
describe(fil.data)
#cor(renamed.raw)
```

```{r}
#data is divided between rural and urban highways
#and solely 400 series highways etc.

#group by highway and then by location
```

```{r}
#MTO divides the highways into four categories: the king's highways, the secondary highways, the tertiary roads, and selected 7000 series highways. the king's highways will be further grouped into the 400 series highways +  the QEW.

library(dplyr)

#select for the four highway types in the dataset
king <- filter(fil.data, hwy.type == "King")
secon <- filter(fil.data, hwy.type == "Sec")
fwy <- filter(fil.data, hwy.type == "Fwy")
tert <- filter(fil.data, hwy.type == "Tert")

#select for the 400, 401, 402, 403, 404, 405, 406, 407, 409, 410, 416, 417, 420, 427
target <- c("400", "401", "402", "403", "404", "405", "406", "407", "409", "410", "416", "417", "420", "427")
four <- filter(fil.data, hwy.num %in% target)

#select for the remaining non-400 series freeways (the QEW) 
qew <- filter(fwy, !(hwy.num %in% target))
```

```{r}
summary(lm(sadt~aadt, data=fil.data))
plot(fil.data$sadt~fil.data$aadt, xlab="SADT", ylab="AADT", main="Plot of SADT and AADT")

```

```{r}
fil.data %>%
  group_by(hwy.type) %>%
  ggvis (~year, ~aadt, stroke = ~factor(hwy.type)) %>%
  layer_smooths() %>%
  title= "Year ~ AADT"
```

```{r}
datadis <- select(fil.data, aadt, sadt, sawdt, wadt)
boxplot(datadis,
        main="Distribution of Data",
        ylab="Value",
        xlab="Data Type")
```

Histogram of Highway Type
```{r}
fil.data %>%
  group_by(hwy.type) %>%
  ggvis (~year, ~aadt, fill=~hwy.type) %>%
  layer_histograms() 
```

```{r}
fil.data %>%
group_by(hwy.type) %>%
ggvis(~year, ~aadt, fill = ~hwy.type) %>%
layer_densities()
```


##3: Visualizations

```{r}
library(ggvis)
library(ggplot2)
```

```{r}
fwy %>% 
  ggvis(~year, ~aadt) %>%
  layer_smooths() %>%
  layer_model_predictions(model = "lm", stroke := "red", se = TRUE)

king %>% 
  ggvis(~year, ~aadt) %>%
  layer_smooths() %>%
  layer_model_predictions(model = "lm", stroke := "red", se = TRUE)

secon %>% 
  ggvis(~year, ~aadt) %>%
  layer_smooths() %>%
  layer_model_predictions(model = "lm", stroke := "red", se = TRUE)

tert %>% 
  ggvis(~year, ~aadt) %>%
  layer_smooths() %>%
  layer_model_predictions(model = "lm", stroke := "red", se = TRUE)
```


##4: Predictions

```{r, include=FALSE}
   # add this chunk to end of mycode.rmd
   file.rename(from="scripts/mycode.md", 
               to="README.md")
```

